services:
  - type: web
    name: casa-liquidity-dashboards
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
